version: '3.3'

services:
  node-express:
    build: .
    image: line-notify:dev
    container_name: line-notify-server
    command: yarn run dev
    ports:
      - 3000:3000
    volumes:
      - ./src:/app/src